char dizi[10]={0x3F,0x06,0x5B,0x4F,0x66,0x6D,0x7D,0x07,0x7F,0x6F};    // 7 SEGMENT DISPLAY KODLARI...
char i=0;      // CHAR TÝPÝNDE Ý DEÐÝÞKENÝ TANIMLANIYOR...
void main()   // ANA PROÐRAM BAÞLANGICI...
{
trisb=0;        // TRISB'NIN BÜTÜN PÝNLERÝ ÇIKIÞ OLARAK AYARLANDI...
trisa.f0=1;     // TRISA'NIN 0. PÝNÝ GÝRÝÞ OLARAK AYARLANDI...
portb=dizi[0];  // PORTB'YE DÝZÝNÝN 0. ELEMANI OLAN SIFIR RAKAMI YÜKLENÝYOR...
CMCON=7;        // KOMPARATÖRLER KAPATILDI...
while(1)        // SONSUZ DÖNGÜ BAÞLANGICI...
        {
        if(porta.f0==0)      //PORTA.F0'DAKÝ PULL-UP DÝRENCÝ 0 MI ( 0V )... ?
                      {
                       i++;        // 1 DEÐÝÞKENÝ 1 ARTTIRILDI...
                       if(i>9)     // Ý DEÐÝÞKENÝ 9 SAYISINDAN BÜYÜK ÝSE...
                             {
                              i=0;   // Ý DEÐÝÞKENÝNÝ 0 YAP...
                             }
                       portb=dizi[i];  //PORTB'YE DÝZÝNÝN Ý DEÐÝÞKENÝ KAÇSA O ELAMANINI YÜKLE...
                       delay_ms(500);  //500 MÝLÝSANÝYE BEKLE...
                      }  //ÝF KOMUTU SONU...
        } // SONSUZ DÖNGÜ SONU...
}  // ANA PROÐRAM SONU...